# Generated by Django 5.1.4 on 2024-12-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtpApp', '0006_alter_customuser_is_active_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='3be36c', max_length=6),
        ),
    ]
