# Generated by Django 5.1.4 on 2024-12-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtpApp', '0012_otptoken_otp_attempts_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otptoken',
            name='otp_attempts',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='b06a5e', max_length=6),
        ),
    ]
