# Generated by Django 5.1.4 on 2024-12-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtpApp', '0013_remove_otptoken_otp_attempts_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='otptoken',
            name='otp_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='7aa4d1', max_length=6),
        ),
    ]
