# Generated by Django 5.1.4 on 2024-12-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtpApp', '0014_otptoken_otp_attempts_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='556ca9', max_length=6),
        ),
    ]
