# Generated by Django 5.1.4 on 2024-12-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OtpApp', '0021_customuser_failed_attempts_customuser_last_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='5a4cfe', max_length=6),
        ),
    ]
